name: blackboard.rest
description: A library for Blackboard's REST API.
version: 0.1.6
author: Joseph B. Axenroth

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  http: ^0.12.0+1

dev_dependencies:
  test: ^1.5.3
